name: Continuous Delivery Conferences and Events
highlighter: rouge
exclude: [README.md]
timezone: Europe/Copenhagen
url: new.code-conf.com
markdown: kramdown
footer: 
  - Brought to you by the folks at
  - /images/praqmalogo.png
  - The continuous development people
praqma:
  url: http://praqma.com

collections:
  events:
    output: true
    permalink: /:path/
    #permalink: /training/:path/
  speakers:
    output: true
  sponsors:
    output: true

defaults:
 -
    scope:
      type: events
    values:
      layout: event
